### ISSUE TITLE
Sequence [A-Z][a-zA-Z]*!"[A-Za-z]+ in input file causes error

### ISSUE THREAD

**Issue by LinguaCelta** [CorCenCC/CyTag#2]
When input text file contains a sequence matching [A-Z][a-zA-Z]*!"[A-Za-z]+, CyTag fails with an error.

For clarity: this occurs when the following example sequences are present in the input file:
>Afal!"a
>A!"araith
>Afal!"Arth

But is not triggered when the following example sequences are present:
>Afal! "a
>A!" Araith
>arth!"Aros

Command-line dump follows:

```
python3 CyTag.py -i TEST.txt -n output -f all

cy_postagger - A part-of-speech (POS) tagger for Welsh texts
------------------------------------------------------------

Producing readings...

From 1 tokens:
--- 1 tokens were given readings
------ 0 tokens only have a single reading pre-CG
--------- 0 of which were definite tags (punctuation, symbols etc.)
------ 0 tokens have multiple readings pre-CG
------ 1 tokens have no readings pre-CG
------ 1 tokens without readings were assumed to be proper nouns
--- 0 tokens are still without readings (marked as 'unknown')

Running VISL CG-3 over 1 tokens...

Mapping CG output tokens to CyTag output formats |################################| 1/1Traceback (most recent call last):
  File "CyTag.py", line 109, in <module>
    process(arguments.input, output_name=arguments.name, directory=arguments.dir, component=arguments.component, output_format=arguments.format)
  File "CyTag.py", line 69, in process
    output = pos_tagger(input_text, output_name, directory, output_format)
  File "/Users/btt/Documents/PhD/CyTag/CyTag/src/cy_postagger.py", line 834, in pos_tagger
    cytag_output = map_cg(cg_output.strip(), mapping_bar)
  File "/Users/btt/Documents/PhD/CyTag/CyTag/src/cy_postagger.py", line 710, in map_cg
    mapped_output += process_cg_token(cg_readingcount, cg_readings[cg_readingcount-1], get_token_position(cg_readings[cg_readingcount-1][1]))
  File "/Users/btt/Documents/PhD/CyTag/CyTag/src/cy_postagger.py", line 666, in process_cg_token
    processed_token = process_double_reading(token_id, token, readings)
  File "/Users/btt/Documents/PhD/CyTag/CyTag/src/cy_postagger.py", line 571, in process_double_reading
    processed_readings = list_readings(readings)
  File "/Users/btt/Documents/PhD/CyTag/CyTag/src/cy_postagger.py", line 520, in list_readings
    if info[-2] == "+":
IndexError: list index out of range
```

**Comment by LinguaCelta** [comment]
Same error seems to be caused by some other strings in input files, too. For example, the strings

>gor-?
>go-?

Couldn't replicate with any other letters preceding the -?, though I didn't try exhaustively.
